// <auto-generated />
using BookRent.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookRent.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240518205154_addProductsToDB")]
    partial class addProductsToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookRent.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Scify"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("BookRent.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = " কাজী নজরুল ইসলাম",
                            Description = "২৫-৭০% ছাড়ে বই সাথে অতিরিক্ত ৩% ছাড় অ্যাপ অর্ডারে। ৫-১৯ মে চলছে শায়েস্তা খাঁ অফার!",
                            Price = 142.0,
                            Title = "অগ্নিবীণা"
                        },
                        new
                        {
                            Id = 2,
                            Author = " কাজী নজরুল ইসলাম",
                            Description = "২৫-৭০% ছাড়ে বই সাথে অতিরিক্ত ৩% ছাড় অ্যাপ অর্ডারে। ৫-১৯ মে চলছে শায়েস্তা খাঁ অফার!",
                            Price = 142.0,
                            Title = "মৃত্যুক্ষুধা"
                        },
                        new
                        {
                            Id = 3,
                            Author = "আহমদ মতিউর রহমান",
                            Description = "২৫-৭০% ছাড়ে বই সাথে অতিরিক্ত ৩% ছাড় অ্যাপ অর্ডারে। ৫-১৯ মে চলছে শায়েস্তা খাঁ অফার!",
                            Price = 200.0,
                            Title = "বিশ্বকবি রবীন্দ্রনাথ ঠাকুর (জীবনীগ্রন্থ)"
                        },
                        new
                        {
                            Id = 4,
                            Author = "আহমদ মতিউর রহমান",
                            Description = "২৫-৭০% ছাড়ে বই সাথে অতিরিক্ত ৩% ছাড় অ্যাপ অর্ডারে। ৫-১৯ মে চলছে শায়েস্তা খাঁ অফার!",
                            Price = 142.0,
                            Title = "গণতন্ত্রের মানসপুত্র হোসেন শহীদ সোহরাওয়ার্দী"
                        },
                        new
                        {
                            Id = 5,
                            Author = "আহমদ মতিউর রহমান",
                            Description = "২৫-৭০% ছাড়ে বই সাথে অতিরিক্ত ৩% ছাড় অ্যাপ অর্ডারে। ৫-১৯ মে চলছে শায়েস্তা খাঁ অফার!",
                            Price = 300.0,
                            Title = "নবাব সিরাজউদ্দৌলার পতনের কারণ ও বাংলার ২০০ বছর"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
